/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Position', 'model/RoleGroup'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Position'), require('./RoleGroup'));
  } else {
    // Browser globals (root is window)
    if (!root.TractionToolsApiV1) {
      root.TractionToolsApiV1 = {};
    }
    root.TractionToolsApiV1.AccountabilityGroup = factory(root.TractionToolsApiV1.ApiClient, root.TractionToolsApiV1.Position, root.TractionToolsApiV1.RoleGroup);
  }
}(this, function(ApiClient, Position, RoleGroup) {
  'use strict';




  /**
   * The AccountabilityGroup model module.
   * @module model/AccountabilityGroup
   * @version v1
   */

  /**
   * Constructs a new <code>AccountabilityGroup</code>.
   * @alias module:model/AccountabilityGroup
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>AccountabilityGroup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountabilityGroup} obj Optional instance to populate.
   * @return {module:model/AccountabilityGroup} The populated <code>AccountabilityGroup</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Id')) {
        obj['Id'] = ApiClient.convertToType(data['Id'], 'Number');
      }
      if (data.hasOwnProperty('Type')) {
        obj['Type'] = ApiClient.convertToType(data['Type'], 'String');
      }
      if (data.hasOwnProperty('Key')) {
        obj['Key'] = ApiClient.convertToType(data['Key'], 'String');
      }
      if (data.hasOwnProperty('Position')) {
        obj['Position'] = Position.constructFromObject(data['Position']);
      }
      if (data.hasOwnProperty('Editable')) {
        obj['Editable'] = ApiClient.convertToType(data['Editable'], 'Boolean');
      }
      if (data.hasOwnProperty('RoleGroups')) {
        obj['RoleGroups'] = ApiClient.convertToType(data['RoleGroups'], [RoleGroup]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} Id
   */
  exports.prototype['Id'] = undefined;
  /**
   * @member {String} Type
   */
  exports.prototype['Type'] = undefined;
  /**
   * @member {String} Key
   */
  exports.prototype['Key'] = undefined;
  /**
   * @member {module:model/Position} Position
   */
  exports.prototype['Position'] = undefined;
  /**
   * @member {Boolean} Editable
   */
  exports.prototype['Editable'] = undefined;
  /**
   * @member {Array.<module:model/RoleGroup>} RoleGroups
   */
  exports.prototype['RoleGroups'] = undefined;



  return exports;
}));


