/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TractionToolsApiV1) {
      root.TractionToolsApiV1 = {};
    }
    root.TractionToolsApiV1.CreateNewQuarter = factory(root.TractionToolsApiV1.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CreateNewQuarter model module.
   * @module model/CreateNewQuarter
   * @version v1
   */

  /**
   * Constructs a new <code>CreateNewQuarter</code>.
   * @alias module:model/CreateNewQuarter
   * @class
   * @param name {String} New Quarter title
   * @param quarterenddate {Date} New Quarter date
   * @param meetingId {Number} Meeting ID
   */
  var exports = function(name, quarterenddate, meetingId) {
    var _this = this;

    _this['name'] = name;
    _this['quarterenddate'] = quarterenddate;
    _this['meetingId'] = meetingId;
  };

  /**
   * Constructs a <code>CreateNewQuarter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateNewQuarter} obj Optional instance to populate.
   * @return {module:model/CreateNewQuarter} The populated <code>CreateNewQuarter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('quarterenddate')) {
        obj['quarterenddate'] = ApiClient.convertToType(data['quarterenddate'], 'Date');
      }
      if (data.hasOwnProperty('meetingId')) {
        obj['meetingId'] = ApiClient.convertToType(data['meetingId'], 'Number');
      }
    }
    return obj;
  }

  /**
   * New Quarter title
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * New Quarter date
   * @member {Date} quarterenddate
   */
  exports.prototype['quarterenddate'] = undefined;
  /**
   * Meeting ID
   * @member {Number} meetingId
   */
  exports.prototype['meetingId'] = undefined;



  return exports;
}));


