/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TractionToolsApiV1) {
      root.TractionToolsApiV1 = {};
    }
    root.TractionToolsApiV1.CreateTodo = factory(root.TractionToolsApiV1.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CreateTodo model module.
   * @module model/CreateTodo
   * @version v1
   */

  /**
   * Constructs a new <code>CreateTodo</code>.
   * @alias module:model/CreateTodo
   * @class
   * @param title {String} To-do title
   */
  var exports = function(title) {
    var _this = this;

    _this['title'] = title;



  };

  /**
   * Constructs a <code>CreateTodo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateTodo} obj Optional instance to populate.
   * @return {module:model/CreateTodo} The populated <code>CreateTodo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('details')) {
        obj['details'] = ApiClient.convertToType(data['details'], 'String');
      }
      if (data.hasOwnProperty('accountableUserId')) {
        obj['accountableUserId'] = ApiClient.convertToType(data['accountableUserId'], 'Number');
      }
      if (data.hasOwnProperty('dueDate')) {
        obj['dueDate'] = ApiClient.convertToType(data['dueDate'], 'Date');
      }
    }
    return obj;
  }

  /**
   * To-do title
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * To-do notes (Default: none)
   * @member {String} details
   */
  exports.prototype['details'] = undefined;
  /**
   * Accountable user (Default: you)
   * @member {Number} accountableUserId
   */
  exports.prototype['accountableUserId'] = undefined;
  /**
   * To-do due date (Default: 7 days)
   * @member {Date} dueDate
   */
  exports.prototype['dueDate'] = undefined;



  return exports;
}));


