/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Issue'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Issue'));
  } else {
    // Browser globals (root is window)
    if (!root.TractionToolsApiV1) {
      root.TractionToolsApiV1 = {};
    }
    root.TractionToolsApiV1.IssuesList = factory(root.TractionToolsApiV1.ApiClient, root.TractionToolsApiV1.Issue);
  }
}(this, function(ApiClient, Issue) {
  'use strict';




  /**
   * The IssuesList model module.
   * @module model/IssuesList
   * @version v1
   */

  /**
   * Constructs a new <code>IssuesList</code>.
   * @alias module:model/IssuesList
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>IssuesList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IssuesList} obj Optional instance to populate.
   * @return {module:model/IssuesList} The populated <code>IssuesList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Id')) {
        obj['Id'] = ApiClient.convertToType(data['Id'], 'Number');
      }
      if (data.hasOwnProperty('Type')) {
        obj['Type'] = ApiClient.convertToType(data['Type'], 'String');
      }
      if (data.hasOwnProperty('Key')) {
        obj['Key'] = ApiClient.convertToType(data['Key'], 'String');
      }
      if (data.hasOwnProperty('Issues')) {
        obj['Issues'] = ApiClient.convertToType(data['Issues'], [Issue]);
      }
      if (data.hasOwnProperty('Prioritization')) {
        obj['Prioritization'] = ApiClient.convertToType(data['Prioritization'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} Id
   */
  exports.prototype['Id'] = undefined;
  /**
   * @member {String} Type
   */
  exports.prototype['Type'] = undefined;
  /**
   * @member {String} Key
   */
  exports.prototype['Key'] = undefined;
  /**
   * @member {Array.<module:model/Issue>} Issues
   */
  exports.prototype['Issues'] = undefined;
  /**
   * @member {module:model/IssuesList.PrioritizationEnum} Prioritization
   */
  exports.prototype['Prioritization'] = undefined;


  /**
   * Allowed values for the <code>Prioritization</code> property.
   * @enum {String}
   * @readonly
   */
  exports.PrioritizationEnum = {
    /**
     * value: "Priority"
     * @const
     */
    "Priority": "Priority",
    /**
     * value: "Rank"
     * @const
     */
    "Rank": "Rank"  };


  return exports;
}));


