/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TractionToolsApiV1) {
      root.TractionToolsApiV1 = {};
    }
    root.TractionToolsApiV1.Page = factory(root.TractionToolsApiV1.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Page model module.
   * @module model/Page
   * @version v1
   */

  /**
   * Constructs a new <code>Page</code>.
   * @alias module:model/Page
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Page</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Page} obj Optional instance to populate.
   * @return {module:model/Page} The populated <code>Page</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Minutes')) {
        obj['Minutes'] = ApiClient.convertToType(data['Minutes'], 'Number');
      }
      if (data.hasOwnProperty('Title')) {
        obj['Title'] = ApiClient.convertToType(data['Title'], 'String');
      }
      if (data.hasOwnProperty('Type')) {
        obj['Type'] = ApiClient.convertToType(data['Type'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} Minutes
   */
  exports.prototype['Minutes'] = undefined;
  /**
   * @member {String} Title
   */
  exports.prototype['Title'] = undefined;
  /**
   * @member {module:model/Page.TypeEnum} Type
   */
  exports.prototype['Type'] = undefined;


  /**
   * Allowed values for the <code>Type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "Segue"
     * @const
     */
    "Segue": "Segue",
    /**
     * value: "Scorecard"
     * @const
     */
    "Scorecard": "Scorecard",
    /**
     * value: "Rock Review"
     * @const
     */
    "Rock Review": "Rock Review",
    /**
     * value: "People Headlines"
     * @const
     */
    "People Headlines": "People Headlines",
    /**
     * value: "To-do List"
     * @const
     */
    "To-do List": "To-do List",
    /**
     * value: "IDS"
     * @const
     */
    "IDS": "IDS",
    /**
     * value: "Conclude"
     * @const
     */
    "Conclude": "Conclude",
    /**
     * value: "Title Page"
     * @const
     */
    "Title Page": "Title Page",
    /**
     * value: "Notes Box"
     * @const
     */
    "Notes Box": "Notes Box",
    /**
     * value: "External Page"
     * @const
     */
    "External Page": "External Page"  };


  return exports;
}));


