/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Role'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Role'));
  } else {
    // Browser globals (root is window)
    if (!root.TractionToolsApiV1) {
      root.TractionToolsApiV1 = {};
    }
    root.TractionToolsApiV1.RoleGroup = factory(root.TractionToolsApiV1.ApiClient, root.TractionToolsApiV1.Role);
  }
}(this, function(ApiClient, Role) {
  'use strict';




  /**
   * The RoleGroup model module.
   * @module model/RoleGroup
   * @version v1
   */

  /**
   * Constructs a new <code>RoleGroup</code>.
   * @alias module:model/RoleGroup
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>RoleGroup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RoleGroup} obj Optional instance to populate.
   * @return {module:model/RoleGroup} The populated <code>RoleGroup</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Id')) {
        obj['Id'] = ApiClient.convertToType(data['Id'], 'Number');
      }
      if (data.hasOwnProperty('Type')) {
        obj['Type'] = ApiClient.convertToType(data['Type'], 'String');
      }
      if (data.hasOwnProperty('Key')) {
        obj['Key'] = ApiClient.convertToType(data['Key'], 'String');
      }
      if (data.hasOwnProperty('AttachType')) {
        obj['AttachType'] = ApiClient.convertToType(data['AttachType'], 'String');
      }
      if (data.hasOwnProperty('AttachId')) {
        obj['AttachId'] = ApiClient.convertToType(data['AttachId'], 'Number');
      }
      if (data.hasOwnProperty('AttachName')) {
        obj['AttachName'] = ApiClient.convertToType(data['AttachName'], 'String');
      }
      if (data.hasOwnProperty('Editable')) {
        obj['Editable'] = ApiClient.convertToType(data['Editable'], 'Boolean');
      }
      if (data.hasOwnProperty('Roles')) {
        obj['Roles'] = ApiClient.convertToType(data['Roles'], [Role]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} Id
   */
  exports.prototype['Id'] = undefined;
  /**
   * @member {String} Type
   */
  exports.prototype['Type'] = undefined;
  /**
   * @member {String} Key
   */
  exports.prototype['Key'] = undefined;
  /**
   * @member {module:model/RoleGroup.AttachTypeEnum} AttachType
   */
  exports.prototype['AttachType'] = undefined;
  /**
   * @member {Number} AttachId
   */
  exports.prototype['AttachId'] = undefined;
  /**
   * @member {String} AttachName
   */
  exports.prototype['AttachName'] = undefined;
  /**
   * @member {Boolean} Editable
   */
  exports.prototype['Editable'] = undefined;
  /**
   * @member {Array.<module:model/Role>} Roles
   */
  exports.prototype['Roles'] = undefined;


  /**
   * Allowed values for the <code>AttachType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AttachTypeEnum = {
    /**
     * value: "Invalid"
     * @const
     */
    "Invalid": "Invalid",
    /**
     * value: "Position"
     * @const
     */
    "Position": "Position",
    /**
     * value: "Team"
     * @const
     */
    "Team": "Team",
    /**
     * value: "User"
     * @const
     */
    "User": "User",
    /**
     * value: "MAX"
     * @const
     */
    "MAX": "MAX"  };


  return exports;
}));


