/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Measurable', 'model/MeasurableOrder', 'model/Score', 'model/Week'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Measurable'), require('./MeasurableOrder'), require('./Score'), require('./Week'));
  } else {
    // Browser globals (root is window)
    if (!root.TractionToolsApiV1) {
      root.TractionToolsApiV1 = {};
    }
    root.TractionToolsApiV1.Scorecard = factory(root.TractionToolsApiV1.ApiClient, root.TractionToolsApiV1.Measurable, root.TractionToolsApiV1.MeasurableOrder, root.TractionToolsApiV1.Score, root.TractionToolsApiV1.Week);
  }
}(this, function(ApiClient, Measurable, MeasurableOrder, Score, Week) {
  'use strict';




  /**
   * The Scorecard model module.
   * @module model/Scorecard
   * @version v1
   */

  /**
   * Constructs a new <code>Scorecard</code>.
   * @alias module:model/Scorecard
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>Scorecard</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Scorecard} obj Optional instance to populate.
   * @return {module:model/Scorecard} The populated <code>Scorecard</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Id')) {
        obj['Id'] = ApiClient.convertToType(data['Id'], 'Number');
      }
      if (data.hasOwnProperty('Type')) {
        obj['Type'] = ApiClient.convertToType(data['Type'], 'String');
      }
      if (data.hasOwnProperty('Key')) {
        obj['Key'] = ApiClient.convertToType(data['Key'], 'String');
      }
      if (data.hasOwnProperty('MeasurableOrder')) {
        obj['MeasurableOrder'] = ApiClient.convertToType(data['MeasurableOrder'], [MeasurableOrder]);
      }
      if (data.hasOwnProperty('Measurables')) {
        obj['Measurables'] = ApiClient.convertToType(data['Measurables'], [Measurable]);
      }
      if (data.hasOwnProperty('Scores')) {
        obj['Scores'] = ApiClient.convertToType(data['Scores'], [Score]);
      }
      if (data.hasOwnProperty('Weeks')) {
        obj['Weeks'] = ApiClient.convertToType(data['Weeks'], [Week]);
      }
      if (data.hasOwnProperty('ReverseScorecard')) {
        obj['ReverseScorecard'] = ApiClient.convertToType(data['ReverseScorecard'], 'Boolean');
      }
      if (data.hasOwnProperty('ScorecardWeekDay')) {
        obj['ScorecardWeekDay'] = ApiClient.convertToType(data['ScorecardWeekDay'], 'String');
      }
      if (data.hasOwnProperty('Period')) {
        obj['Period'] = ApiClient.convertToType(data['Period'], 'String');
      }
      if (data.hasOwnProperty('DateFormat1')) {
        obj['DateFormat1'] = ApiClient.convertToType(data['DateFormat1'], 'String');
      }
      if (data.hasOwnProperty('DateFormat2')) {
        obj['DateFormat2'] = ApiClient.convertToType(data['DateFormat2'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} Id
   */
  exports.prototype['Id'] = undefined;
  /**
   * @member {String} Type
   */
  exports.prototype['Type'] = undefined;
  /**
   * @member {String} Key
   */
  exports.prototype['Key'] = undefined;
  /**
   * @member {Array.<module:model/MeasurableOrder>} MeasurableOrder
   */
  exports.prototype['MeasurableOrder'] = undefined;
  /**
   * @member {Array.<module:model/Measurable>} Measurables
   */
  exports.prototype['Measurables'] = undefined;
  /**
   * @member {Array.<module:model/Score>} Scores
   */
  exports.prototype['Scores'] = undefined;
  /**
   * @member {Array.<module:model/Week>} Weeks
   */
  exports.prototype['Weeks'] = undefined;
  /**
   * @member {Boolean} ReverseScorecard
   */
  exports.prototype['ReverseScorecard'] = undefined;
  /**
   * @member {module:model/Scorecard.ScorecardWeekDayEnum} ScorecardWeekDay
   */
  exports.prototype['ScorecardWeekDay'] = undefined;
  /**
   * @member {String} Period
   */
  exports.prototype['Period'] = undefined;
  /**
   * @member {String} DateFormat1
   */
  exports.prototype['DateFormat1'] = undefined;
  /**
   * @member {String} DateFormat2
   */
  exports.prototype['DateFormat2'] = undefined;


  /**
   * Allowed values for the <code>ScorecardWeekDay</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ScorecardWeekDayEnum = {
    /**
     * value: "Sunday"
     * @const
     */
    "Sunday": "Sunday",
    /**
     * value: "Monday"
     * @const
     */
    "Monday": "Monday",
    /**
     * value: "Tuesday"
     * @const
     */
    "Tuesday": "Tuesday",
    /**
     * value: "Wednesday"
     * @const
     */
    "Wednesday": "Wednesday",
    /**
     * value: "Thursday"
     * @const
     */
    "Thursday": "Thursday",
    /**
     * value: "Friday"
     * @const
     */
    "Friday": "Friday",
    /**
     * value: "Saturday"
     * @const
     */
    "Saturday": "Saturday"  };


  return exports;
}));


