/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TractionToolsApiV1) {
      root.TractionToolsApiV1 = {};
    }
    root.TractionToolsApiV1.SearchResult = factory(root.TractionToolsApiV1.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SearchResult model module.
   * @module model/SearchResult
   * @version v1
   */

  /**
   * Constructs a new <code>SearchResult</code>.
   * @alias module:model/SearchResult
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>SearchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchResult} obj Optional instance to populate.
   * @return {module:model/SearchResult} The populated <code>SearchResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Id')) {
        obj['Id'] = ApiClient.convertToType(data['Id'], 'Number');
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('Description')) {
        obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
      }
      if (data.hasOwnProperty('OrganizationId')) {
        obj['OrganizationId'] = ApiClient.convertToType(data['OrganizationId'], 'Number');
      }
      if (data.hasOwnProperty('Organization')) {
        obj['Organization'] = ApiClient.convertToType(data['Organization'], 'String');
      }
      if (data.hasOwnProperty('Email')) {
        obj['Email'] = ApiClient.convertToType(data['Email'], 'String');
      }
      if (data.hasOwnProperty('ImageUrl')) {
        obj['ImageUrl'] = ApiClient.convertToType(data['ImageUrl'], 'String');
      }
      if (data.hasOwnProperty('AltIcon')) {
        obj['AltIcon'] = ApiClient.convertToType(data['AltIcon'], 'String');
      }
      if (data.hasOwnProperty('ResultType')) {
        obj['ResultType'] = ApiClient.convertToType(data['ResultType'], 'String');
      }
      if (data.hasOwnProperty('ItemName')) {
        obj['ItemName'] = ApiClient.convertToType(data['ItemName'], 'String');
      }
      if (data.hasOwnProperty('ItemImageUrl')) {
        obj['ItemImageUrl'] = ApiClient.convertToType(data['ItemImageUrl'], 'String');
      }
      if (data.hasOwnProperty('ItemValue')) {
        obj['ItemValue'] = ApiClient.convertToType(data['ItemValue'], 'String');
      }
      if (data.hasOwnProperty('ItemDescription')) {
        obj['ItemDescription'] = ApiClient.convertToType(data['ItemDescription'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} Id
   */
  exports.prototype['Id'] = undefined;
  /**
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * @member {String} Description
   */
  exports.prototype['Description'] = undefined;
  /**
   * @member {Number} OrganizationId
   */
  exports.prototype['OrganizationId'] = undefined;
  /**
   * @member {String} Organization
   */
  exports.prototype['Organization'] = undefined;
  /**
   * @member {String} Email
   */
  exports.prototype['Email'] = undefined;
  /**
   * @member {String} ImageUrl
   */
  exports.prototype['ImageUrl'] = undefined;
  /**
   * @member {String} AltIcon
   */
  exports.prototype['AltIcon'] = undefined;
  /**
   * @member {module:model/SearchResult.ResultTypeEnum} ResultType
   */
  exports.prototype['ResultType'] = undefined;
  /**
   * @member {String} ItemName
   */
  exports.prototype['ItemName'] = undefined;
  /**
   * @member {String} ItemImageUrl
   */
  exports.prototype['ItemImageUrl'] = undefined;
  /**
   * @member {String} ItemValue
   */
  exports.prototype['ItemValue'] = undefined;
  /**
   * @member {String} ItemDescription
   */
  exports.prototype['ItemDescription'] = undefined;


  /**
   * Allowed values for the <code>ResultType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ResultTypeEnum = {
    /**
     * value: "Invalid"
     * @const
     */
    "Invalid": "Invalid",
    /**
     * value: "User"
     * @const
     */
    "User": "User",
    /**
     * value: "Organization"
     * @const
     */
    "Organization": "Organization",
    /**
     * value: "Team"
     * @const
     */
    "Team": "Team",
    /**
     * value: "Position"
     * @const
     */
    "Position": "Position",
    /**
     * value: "SearchResult"
     * @const
     */
    "SearchResult": "SearchResult"  };


  return exports;
}));


