/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TractionToolsApiV1) {
      root.TractionToolsApiV1 = {};
    }
    root.TractionToolsApiV1.UpdateRock = factory(root.TractionToolsApiV1.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UpdateRock model module.
   * @module model/UpdateRock
   * @version v1
   */

  /**
   * Constructs a new <code>UpdateRock</code>.
   * @alias module:model/UpdateRock
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>UpdateRock</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateRock} obj Optional instance to populate.
   * @return {module:model/UpdateRock} The populated <code>UpdateRock</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('accountableUserId')) {
        obj['accountableUserId'] = ApiClient.convertToType(data['accountableUserId'], 'Number');
      }
      if (data.hasOwnProperty('completion')) {
        obj['completion'] = ApiClient.convertToType(data['completion'], 'String');
      }
    }
    return obj;
  }

  /**
   * Rock name
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * Rock owner (Default: you)
   * @member {Number} accountableUserId
   */
  exports.prototype['accountableUserId'] = undefined;
  /**
   * Rock completion status
   * @member {module:model/UpdateRock.CompletionEnum} completion
   */
  exports.prototype['completion'] = undefined;


  /**
   * Allowed values for the <code>completion</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CompletionEnum = {
    /**
     * value: "Indeterminate"
     * @const
     */
    "Indeterminate": "Indeterminate",
    /**
     * value: "AtRisk"
     * @const
     */
    "AtRisk": "AtRisk",
    /**
     * value: "OnTrack"
     * @const
     */
    "OnTrack": "OnTrack",
    /**
     * value: "Complete"
     * @const
     */
    "Complete": "Complete"  };


  return exports;
}));


