/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TractionToolsApiV1) {
      root.TractionToolsApiV1 = {};
    }
    root.TractionToolsApiV1.UpdateIssue = factory(root.TractionToolsApiV1.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UpdateIssue model module.
   * @module model/UpdateIssue
   * @version v1
   */

  /**
   * Constructs a new <code>UpdateIssue</code>.
   * @alias module:model/UpdateIssue
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>UpdateIssue</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateIssue} obj Optional instance to populate.
   * @return {module:model/UpdateIssue} The populated <code>UpdateIssue</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('ownerId')) {
        obj['ownerId'] = ApiClient.convertToType(data['ownerId'], 'Number');
      }
      if (data.hasOwnProperty('compartment')) {
        obj['compartment'] = ApiClient.convertToType(data['compartment'], 'String');
      }
    }
    return obj;
  }

  /**
   * Title for the issue
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * Owner's user ID
   * @member {Number} ownerId
   */
  exports.prototype['ownerId'] = undefined;
  /**
   * The compartment this issue belongs to. Short Term = Level 10, Long Term = V/TO
   * @member {module:model/UpdateIssue.CompartmentEnum} compartment
   */
  exports.prototype['compartment'] = undefined;


  /**
   * Allowed values for the <code>compartment</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CompartmentEnum = {
    /**
     * value: "ShortTerm"
     * @const
     */
    "ShortTerm": "ShortTerm",
    /**
     * value: "LongTerm"
     * @const
     */
    "LongTerm": "LongTerm"  };


  return exports;
}));


