/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TractionToolsApiV1);
  }
}(this, function(expect, TractionToolsApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TractionToolsApiV1.CreateNewQuarter();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateNewQuarter', function() {
    it('should create an instance of CreateNewQuarter', function() {
      // uncomment below and update the code to test CreateNewQuarter
      //var instance = new TractionToolsApiV1.CreateNewQuarter();
      //expect(instance).to.be.a(TractionToolsApiV1.CreateNewQuarter);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new TractionToolsApiV1.CreateNewQuarter();
      //expect(instance).to.be();
    });

    it('should have the property quarterenddate (base name: "quarterenddate")', function() {
      // uncomment below and update the code to test the property quarterenddate
      //var instance = new TractionToolsApiV1.CreateNewQuarter();
      //expect(instance).to.be();
    });

    it('should have the property meetingId (base name: "meetingId")', function() {
      // uncomment below and update the code to test the property meetingId
      //var instance = new TractionToolsApiV1.CreateNewQuarter();
      //expect(instance).to.be();
    });

  });

}));
