/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TractionToolsApiV1);
  }
}(this, function(expect, TractionToolsApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TractionToolsApiV1.Meeting();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Meeting', function() {
    it('should create an instance of Meeting', function() {
      // uncomment below and update the code to test Meeting
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be.a(TractionToolsApiV1.Meeting);
    });

    it('should have the property id (base name: "Id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "Type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property key (base name: "Key")', function() {
      // uncomment below and update the code to test the property key
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property createTime (base name: "CreateTime")', function() {
      // uncomment below and update the code to test the property createTime
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "CreatedBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property basics (base name: "Basics")', function() {
      // uncomment below and update the code to test the property basics
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property attendees (base name: "Attendees")', function() {
      // uncomment below and update the code to test the property attendees
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property scorecard (base name: "Scorecard")', function() {
      // uncomment below and update the code to test the property scorecard
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property notes (base name: "Notes")', function() {
      // uncomment below and update the code to test the property notes
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property rocks (base name: "Rocks")', function() {
      // uncomment below and update the code to test the property rocks
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property todos (base name: "Todos")', function() {
      // uncomment below and update the code to test the property todos
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property milestones (base name: "Milestones")', function() {
      // uncomment below and update the code to test the property milestones
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property headlines (base name: "Headlines")', function() {
      // uncomment below and update the code to test the property headlines
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property issuesList (base name: "IssuesList")', function() {
      // uncomment below and update the code to test the property issuesList
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property headlinesUrl (base name: "HeadlinesUrl")', function() {
      // uncomment below and update the code to test the property headlinesUrl
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property headlineType (base name: "HeadlineType")', function() {
      // uncomment below and update the code to test the property headlineType
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property vtoId (base name: "VtoId")', function() {
      // uncomment below and update the code to test the property vtoId
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property pages (base name: "Pages")', function() {
      // uncomment below and update the code to test the property pages
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

    it('should have the property meetingType (base name: "MeetingType")', function() {
      // uncomment below and update the code to test the property meetingType
      //var instance = new TractionToolsApiV1.Meeting();
      //expect(instance).to.be();
    });

  });

}));
