/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TractionToolsApiV1);
  }
}(this, function(expect, TractionToolsApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TractionToolsApiV1.Scorecard();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Scorecard', function() {
    it('should create an instance of Scorecard', function() {
      // uncomment below and update the code to test Scorecard
      //var instance = new TractionToolsApiV1.Scorecard();
      //expect(instance).to.be.a(TractionToolsApiV1.Scorecard);
    });

    it('should have the property id (base name: "Id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TractionToolsApiV1.Scorecard();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "Type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new TractionToolsApiV1.Scorecard();
      //expect(instance).to.be();
    });

    it('should have the property key (base name: "Key")', function() {
      // uncomment below and update the code to test the property key
      //var instance = new TractionToolsApiV1.Scorecard();
      //expect(instance).to.be();
    });

    it('should have the property measurableOrder (base name: "MeasurableOrder")', function() {
      // uncomment below and update the code to test the property measurableOrder
      //var instance = new TractionToolsApiV1.Scorecard();
      //expect(instance).to.be();
    });

    it('should have the property measurables (base name: "Measurables")', function() {
      // uncomment below and update the code to test the property measurables
      //var instance = new TractionToolsApiV1.Scorecard();
      //expect(instance).to.be();
    });

    it('should have the property scores (base name: "Scores")', function() {
      // uncomment below and update the code to test the property scores
      //var instance = new TractionToolsApiV1.Scorecard();
      //expect(instance).to.be();
    });

    it('should have the property weeks (base name: "Weeks")', function() {
      // uncomment below and update the code to test the property weeks
      //var instance = new TractionToolsApiV1.Scorecard();
      //expect(instance).to.be();
    });

    it('should have the property reverseScorecard (base name: "ReverseScorecard")', function() {
      // uncomment below and update the code to test the property reverseScorecard
      //var instance = new TractionToolsApiV1.Scorecard();
      //expect(instance).to.be();
    });

    it('should have the property scorecardWeekDay (base name: "ScorecardWeekDay")', function() {
      // uncomment below and update the code to test the property scorecardWeekDay
      //var instance = new TractionToolsApiV1.Scorecard();
      //expect(instance).to.be();
    });

    it('should have the property period (base name: "Period")', function() {
      // uncomment below and update the code to test the property period
      //var instance = new TractionToolsApiV1.Scorecard();
      //expect(instance).to.be();
    });

    it('should have the property dateFormat1 (base name: "DateFormat1")', function() {
      // uncomment below and update the code to test the property dateFormat1
      //var instance = new TractionToolsApiV1.Scorecard();
      //expect(instance).to.be();
    });

    it('should have the property dateFormat2 (base name: "DateFormat2")', function() {
      // uncomment below and update the code to test the property dateFormat2
      //var instance = new TractionToolsApiV1.Scorecard();
      //expect(instance).to.be();
    });

  });

}));
