/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TractionToolsApiV1);
  }
}(this, function(expect, TractionToolsApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TractionToolsApiV1.Score();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Score', function() {
    it('should create an instance of Score', function() {
      // uncomment below and update the code to test Score
      //var instance = new TractionToolsApiV1.Score();
      //expect(instance).to.be.a(TractionToolsApiV1.Score);
    });

    it('should have the property id (base name: "Id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TractionToolsApiV1.Score();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "Type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new TractionToolsApiV1.Score();
      //expect(instance).to.be();
    });

    it('should have the property key (base name: "Key")', function() {
      // uncomment below and update the code to test the property key
      //var instance = new TractionToolsApiV1.Score();
      //expect(instance).to.be();
    });

    it('should have the property forWeek (base name: "ForWeek")', function() {
      // uncomment below and update the code to test the property forWeek
      //var instance = new TractionToolsApiV1.Score();
      //expect(instance).to.be();
    });

    it('should have the property week (base name: "Week")', function() {
      // uncomment below and update the code to test the property week
      //var instance = new TractionToolsApiV1.Score();
      //expect(instance).to.be();
    });

    it('should have the property measurableId (base name: "MeasurableId")', function() {
      // uncomment below and update the code to test the property measurableId
      //var instance = new TractionToolsApiV1.Score();
      //expect(instance).to.be();
    });

    it('should have the property dateEntered (base name: "DateEntered")', function() {
      // uncomment below and update the code to test the property dateEntered
      //var instance = new TractionToolsApiV1.Score();
      //expect(instance).to.be();
    });

    it('should have the property measured (base name: "Measured")', function() {
      // uncomment below and update the code to test the property measured
      //var instance = new TractionToolsApiV1.Score();
      //expect(instance).to.be();
    });

    it('should have the property disabled (base name: "Disabled")', function() {
      // uncomment below and update the code to test the property disabled
      //var instance = new TractionToolsApiV1.Score();
      //expect(instance).to.be();
    });

    it('should have the property direction (base name: "Direction")', function() {
      // uncomment below and update the code to test the property direction
      //var instance = new TractionToolsApiV1.Score();
      //expect(instance).to.be();
    });

    it('should have the property target (base name: "Target")', function() {
      // uncomment below and update the code to test the property target
      //var instance = new TractionToolsApiV1.Score();
      //expect(instance).to.be();
    });

    it('should have the property altTarget (base name: "AltTarget")', function() {
      // uncomment below and update the code to test the property altTarget
      //var instance = new TractionToolsApiV1.Score();
      //expect(instance).to.be();
    });

  });

}));
