/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TractionToolsApiV1);
  }
}(this, function(expect, TractionToolsApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TractionToolsApiV1.SearchResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SearchResult', function() {
    it('should create an instance of SearchResult', function() {
      // uncomment below and update the code to test SearchResult
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be.a(TractionToolsApiV1.SearchResult);
    });

    it('should have the property id (base name: "Id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "Description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be();
    });

    it('should have the property organizationId (base name: "OrganizationId")', function() {
      // uncomment below and update the code to test the property organizationId
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be();
    });

    it('should have the property organization (base name: "Organization")', function() {
      // uncomment below and update the code to test the property organization
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "Email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be();
    });

    it('should have the property imageUrl (base name: "ImageUrl")', function() {
      // uncomment below and update the code to test the property imageUrl
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be();
    });

    it('should have the property altIcon (base name: "AltIcon")', function() {
      // uncomment below and update the code to test the property altIcon
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be();
    });

    it('should have the property resultType (base name: "ResultType")', function() {
      // uncomment below and update the code to test the property resultType
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be();
    });

    it('should have the property itemName (base name: "ItemName")', function() {
      // uncomment below and update the code to test the property itemName
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be();
    });

    it('should have the property itemImageUrl (base name: "ItemImageUrl")', function() {
      // uncomment below and update the code to test the property itemImageUrl
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be();
    });

    it('should have the property itemValue (base name: "ItemValue")', function() {
      // uncomment below and update the code to test the property itemValue
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be();
    });

    it('should have the property itemDescription (base name: "ItemDescription")', function() {
      // uncomment below and update the code to test the property itemDescription
      //var instance = new TractionToolsApiV1.SearchResult();
      //expect(instance).to.be();
    });

  });

}));
