/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TractionToolsApiV1);
  }
}(this, function(expect, TractionToolsApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TractionToolsApiV1.HeadlinesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HeadlinesApi', function() {
    describe('headlinesGetHeadline', function() {
      it('should call headlinesGetHeadline successfully', function(done) {
        //uncomment below and update the code to test headlinesGetHeadline
        //instance.headlinesGetHeadline(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('headlinesGetMineHeadlines', function() {
      it('should call headlinesGetMineHeadlines successfully', function(done) {
        //uncomment below and update the code to test headlinesGetMineHeadlines
        //instance.headlinesGetMineHeadlines(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('headlinesGetUserHeadlines', function() {
      it('should call headlinesGetUserHeadlines successfully', function(done) {
        //uncomment below and update the code to test headlinesGetUserHeadlines
        //instance.headlinesGetUserHeadlines(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('headlinesRemoveHeadlines', function() {
      it('should call headlinesRemoveHeadlines successfully', function(done) {
        //uncomment below and update the code to test headlinesRemoveHeadlines
        //instance.headlinesRemoveHeadlines(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('headlinesUpdateHeadlines', function() {
      it('should call headlinesUpdateHeadlines successfully', function(done) {
        //uncomment below and update the code to test headlinesUpdateHeadlines
        //instance.headlinesUpdateHeadlines(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
