/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TractionToolsApiV1);
  }
}(this, function(expect, TractionToolsApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TractionToolsApiV1.Measurables_Api();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Measurables_Api', function() {
    describe('measurablesCreateMeasurable', function() {
      it('should call measurablesCreateMeasurable successfully', function(done) {
        //uncomment below and update the code to test measurablesCreateMeasurable
        //instance.measurablesCreateMeasurable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('measurablesGet', function() {
      it('should call measurablesGet successfully', function(done) {
        //uncomment below and update the code to test measurablesGet
        //instance.measurablesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('measurablesGetMeasurableScores', function() {
      it('should call measurablesGetMeasurableScores successfully', function(done) {
        //uncomment below and update the code to test measurablesGetMeasurableScores
        //instance.measurablesGetMeasurableScores(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('measurablesGetMineMeasureables', function() {
      it('should call measurablesGetMineMeasureables successfully', function(done) {
        //uncomment below and update the code to test measurablesGetMineMeasureables
        //instance.measurablesGetMineMeasureables(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('measurablesGetUserMeasureables', function() {
      it('should call measurablesGetUserMeasureables successfully', function(done) {
        //uncomment below and update the code to test measurablesGetUserMeasureables
        //instance.measurablesGetUserMeasureables(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('measurablesUpdateMeasurable', function() {
      it('should call measurablesUpdateMeasurable successfully', function(done) {
        //uncomment below and update the code to test measurablesUpdateMeasurable
        //instance.measurablesUpdateMeasurable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('measurablesUpdateScore', function() {
      it('should call measurablesUpdateScore successfully', function(done) {
        //uncomment below and update the code to test measurablesUpdateScore
        //instance.measurablesUpdateScore(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
