/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TractionToolsApiV1);
  }
}(this, function(expect, TractionToolsApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TractionToolsApiV1.PositionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PositionApi', function() {
    describe('positionAddPositionRoles', function() {
      it('should call positionAddPositionRoles successfully', function(done) {
        //uncomment below and update the code to test positionAddPositionRoles
        //instance.positionAddPositionRoles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('positionCreatePosition', function() {
      it('should call positionCreatePosition successfully', function(done) {
        //uncomment below and update the code to test positionCreatePosition
        //instance.positionCreatePosition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('positionGetMinePosition', function() {
      it('should call positionGetMinePosition successfully', function(done) {
        //uncomment below and update the code to test positionGetMinePosition
        //instance.positionGetMinePosition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('positionGetPositionRoles', function() {
      it('should call positionGetPositionRoles successfully', function(done) {
        //uncomment below and update the code to test positionGetPositionRoles
        //instance.positionGetPositionRoles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('positionGetPositions', function() {
      it('should call positionGetPositions successfully', function(done) {
        //uncomment below and update the code to test positionGetPositions
        //instance.positionGetPositions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('positionUpdatePositions', function() {
      it('should call positionUpdatePositions successfully', function(done) {
        //uncomment below and update the code to test positionUpdatePositions
        //instance.positionUpdatePositions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
