/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TractionToolsApiV1);
  }
}(this, function(expect, TractionToolsApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TractionToolsApiV1.RocksApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RocksApi', function() {
    describe('rocksAddRocksMilestones', function() {
      it('should call rocksAddRocksMilestones successfully', function(done) {
        //uncomment below and update the code to test rocksAddRocksMilestones
        //instance.rocksAddRocksMilestones(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rocksArchiveRock', function() {
      it('should call rocksArchiveRock successfully', function(done) {
        //uncomment below and update the code to test rocksArchiveRock
        //instance.rocksArchiveRock(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rocksCreateRock', function() {
      it('should call rocksCreateRock successfully', function(done) {
        //uncomment below and update the code to test rocksCreateRock
        //instance.rocksCreateRock(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rocksDeleteRocks', function() {
      it('should call rocksDeleteRocks successfully', function(done) {
        //uncomment below and update the code to test rocksDeleteRocks
        //instance.rocksDeleteRocks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rocksGetArchivedRocksForUser', function() {
      it('should call rocksGetArchivedRocksForUser successfully', function(done) {
        //uncomment below and update the code to test rocksGetArchivedRocksForUser
        //instance.rocksGetArchivedRocksForUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rocksGetRock', function() {
      it('should call rocksGetRock successfully', function(done) {
        //uncomment below and update the code to test rocksGetRock
        //instance.rocksGetRock(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rocksGetRocksForUser', function() {
      it('should call rocksGetRocksForUser successfully', function(done) {
        //uncomment below and update the code to test rocksGetRocksForUser
        //instance.rocksGetRocksForUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rocksGetRocksMilestones', function() {
      it('should call rocksGetRocksMilestones successfully', function(done) {
        //uncomment below and update the code to test rocksGetRocksMilestones
        //instance.rocksGetRocksMilestones(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rocksGetYourArchivedRocks', function() {
      it('should call rocksGetYourArchivedRocks successfully', function(done) {
        //uncomment below and update the code to test rocksGetYourArchivedRocks
        //instance.rocksGetYourArchivedRocks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rocksGetYourRocks', function() {
      it('should call rocksGetYourRocks successfully', function(done) {
        //uncomment below and update the code to test rocksGetYourRocks
        //instance.rocksGetYourRocks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rocksRestoreRock', function() {
      it('should call rocksRestoreRock successfully', function(done) {
        //uncomment below and update the code to test rocksRestoreRock
        //instance.rocksRestoreRock(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('rocksUpdateRocks', function() {
      it('should call rocksUpdateRocks successfully', function(done) {
        //uncomment below and update the code to test rocksUpdateRocks
        //instance.rocksUpdateRocks(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
