/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TractionToolsApiV1);
  }
}(this, function(expect, TractionToolsApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TractionToolsApiV1.SeatsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SeatsApi', function() {
    describe('seatsAttachDirectReport', function() {
      it('should call seatsAttachDirectReport successfully', function(done) {
        //uncomment below and update the code to test seatsAttachDirectReport
        //instance.seatsAttachDirectReport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seatsAttachPosition', function() {
      it('should call seatsAttachPosition successfully', function(done) {
        //uncomment below and update the code to test seatsAttachPosition
        //instance.seatsAttachPosition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seatsAttachUser', function() {
      it('should call seatsAttachUser successfully', function(done) {
        //uncomment below and update the code to test seatsAttachUser
        //instance.seatsAttachUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seatsDetachUser', function() {
      it('should call seatsDetachUser successfully', function(done) {
        //uncomment below and update the code to test seatsDetachUser
        //instance.seatsDetachUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seatsGetPosition', function() {
      it('should call seatsGetPosition successfully', function(done) {
        //uncomment below and update the code to test seatsGetPosition
        //instance.seatsGetPosition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seatsGetSeat', function() {
      it('should call seatsGetSeat successfully', function(done) {
        //uncomment below and update the code to test seatsGetSeat
        //instance.seatsGetSeat(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seatsGetSeatUser', function() {
      it('should call seatsGetSeatUser successfully', function(done) {
        //uncomment below and update the code to test seatsGetSeatUser
        //instance.seatsGetSeatUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seatsGetSeatsForMe', function() {
      it('should call seatsGetSeatsForMe successfully', function(done) {
        //uncomment below and update the code to test seatsGetSeatsForMe
        //instance.seatsGetSeatsForMe(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seatsGetSeatsForUser', function() {
      it('should call seatsGetSeatsForUser successfully', function(done) {
        //uncomment below and update the code to test seatsGetSeatsForUser
        //instance.seatsGetSeatsForUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seatsRemovePosition', function() {
      it('should call seatsRemovePosition successfully', function(done) {
        //uncomment below and update the code to test seatsRemovePosition
        //instance.seatsRemovePosition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('seatsRemoveSeat', function() {
      it('should call seatsRemoveSeat successfully', function(done) {
        //uncomment below and update the code to test seatsRemoveSeat
        //instance.seatsRemoveSeat(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
