/**
 * Traction Tools API - V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.6-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TractionToolsApiV1);
  }
}(this, function(expect, TractionToolsApiV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TractionToolsApiV1.TeamsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TeamsApi', function() {
    describe('teamsAddTeam', function() {
      it('should call teamsAddTeam successfully', function(done) {
        //uncomment below and update the code to test teamsAddTeam
        //instance.teamsAddTeam(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsAddTeamMember', function() {
      it('should call teamsAddTeamMember successfully', function(done) {
        //uncomment below and update the code to test teamsAddTeamMember
        //instance.teamsAddTeamMember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsGetTeamMembers', function() {
      it('should call teamsGetTeamMembers successfully', function(done) {
        //uncomment below and update the code to test teamsGetTeamMembers
        //instance.teamsGetTeamMembers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsGetTeams', function() {
      it('should call teamsGetTeams successfully', function(done) {
        //uncomment below and update the code to test teamsGetTeams
        //instance.teamsGetTeams(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsRemoveTeamMember', function() {
      it('should call teamsRemoveTeamMember successfully', function(done) {
        //uncomment below and update the code to test teamsRemoveTeamMember
        //instance.teamsRemoveTeamMember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('teamsUpdateTeam', function() {
      it('should call teamsUpdateTeam successfully', function(done) {
        //uncomment below and update the code to test teamsUpdateTeam
        //instance.teamsUpdateTeam(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
